# config/elastic_apm.yml:
#
# # Set service name - allowed characters: a-z, A-Z, 0-9, -, _ and space
# # Defaults to the name of your Rails app
service_name: 'PoC'
#
# # Use if APM Server requires a token
# # secret_token: ''
#
# # Set custom APM Server URL (default: http://localhost:8200)
server_url: 'http://ey-utility-Testing:8200'
